<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>libsigc++: Member List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="doxygen-extra.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">libsigc++
   &#160;<span id="projectnumber">3.2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */</script>
<div id="main-nav"></div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacesigc.html">sigc</a></li><li class="navelem"><a class="el" href="structsigc_1_1exception__catch__functor.html">exception_catch_functor</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt; Member List</div>  </div>
</div><!--header-->
<div class="contents">

<p>This is the complete list of members for <a class="el" href="structsigc_1_1exception__catch__functor.html">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt;</a>, including all inherited members.</p>
<table class="directory">
  <tr class="even"><td class="entry"><a class="el" href="structsigc_1_1adapts.html#a90e81ef167e1c3959168570fc533d4a9">adapts</a>(const T_functor &amp; functor)</td><td class="entry"><a class="el" href="structsigc_1_1adapts.html">sigc::adapts&lt; T_functor &gt;</a></td><td class="entry"><span class="mlabel">inline</span><span class="mlabel">explicit</span></td></tr>
  <tr><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html#a1bfd8dc4fc7a17006013d646be3cec1f">catcher_</a></td><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt;</a></td><td class="entry"></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html#a8d1d3bd860ba6c8bba9ae7655f4dc3a5">exception_catch_functor</a>(const T_functor &amp; func, const T_catcher &amp; catcher)</td><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="structsigc_1_1adapts.html#a2f4b37eb160708baf17de57f2abce7a7">functor_</a></td><td class="entry"><a class="el" href="structsigc_1_1adapts.html">sigc::adapts&lt; T_functor &gt;</a></td><td class="entry"><span class="mlabel">mutable</span></td></tr>
  <tr class="even"><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html#aa7d768aae8b73b5853c8f223f3eeef7f">operator()</a>()</td><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
  <tr><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html#a5784f84ee16758b747e77b89667bbee6">operator()</a>(T_arg... a)</td><td class="entry"><a class="el" href="structsigc_1_1exception__catch__functor.html">sigc::exception_catch_functor&lt; T_functor, T_catcher &gt;</a></td><td class="entry"><span class="mlabel">inline</span></td></tr>
</table></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Fri Feb 11 2022 16:14:06 for libsigc++ by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
