<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>libsigc++: sigc::type_trait&lt; T_type &amp; &gt; Struct Template Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
<link href="doxygen-extra.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">libsigc++
   &#160;<span id="projectnumber">3.2.0</span>
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',false,false,'search.php','Search');
});
/* @license-end */</script>
<div id="main-nav"></div>
<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacesigc.html">sigc</a></li><li class="navelem"><a class="el" href="structsigc_1_1type__trait_3_01T__type_01_6_01_4.html">type_trait&lt; T_type &amp; &gt;</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-types">Public Types</a> &#124;
<a href="structsigc_1_1type__trait_3_01T__type_01_6_01_4-members.html">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">sigc::type_trait&lt; T_type &amp; &gt; Struct Template Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><code>#include &lt;sigc++/type_traits.h&gt;</code></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-types"></a>
Public Types</h2></td></tr>
<tr class="memitem:a142c6b05d842c93a0da4dbd04d529409"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structsigc_1_1type__trait_3_01T__type_01_6_01_4.html#a142c6b05d842c93a0da4dbd04d529409">pass</a> = T_type &amp;</td></tr>
<tr class="separator:a142c6b05d842c93a0da4dbd04d529409"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a966fa5c1414593811fee9a7e4cb0987f"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="structsigc_1_1type__trait_3_01T__type_01_6_01_4.html#a966fa5c1414593811fee9a7e4cb0987f">take</a> = T_type &amp;</td></tr>
<tr class="separator:a966fa5c1414593811fee9a7e4cb0987f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Member Typedef Documentation</h2>
<a id="a142c6b05d842c93a0da4dbd04d529409"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a142c6b05d842c93a0da4dbd04d529409">&#9670;&#160;</a></span>pass</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template &lt;typename T_type &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="structsigc_1_1type__trait.html">sigc::type_trait</a>&lt; T_type &amp; &gt;::<a class="el" href="structsigc_1_1type__trait_3_01T__type_01_6_01_4.html#a142c6b05d842c93a0da4dbd04d529409">pass</a> =  T_type&amp;</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
<a id="a966fa5c1414593811fee9a7e4cb0987f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a966fa5c1414593811fee9a7e4cb0987f">&#9670;&#160;</a></span>take</h2>

<div class="memitem">
<div class="memproto">
<div class="memtemplate">
template &lt;typename T_type &gt; </div>
      <table class="memname">
        <tr>
          <td class="memname">using <a class="el" href="structsigc_1_1type__trait.html">sigc::type_trait</a>&lt; T_type &amp; &gt;::<a class="el" href="structsigc_1_1type__trait_3_01T__type_01_6_01_4.html#a966fa5c1414593811fee9a7e4cb0987f">take</a> =  T_type&amp;</td>
        </tr>
      </table>
</div><div class="memdoc">

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated on Fri Feb 11 2022 16:14:06 for libsigc++ by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
