name: "CI: meson: gcc 9"

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        # Prevent blocking apt install on a question during configuring of tzdata.
        export ENV DEBIAN_FRONTEND=noninteractive
        sudo apt update
        sudo apt install libxml2-utils docbook5-xml docbook-xsl mm-common g++-9 ninja-build python3-setuptools python3-pip --yes
        # Ubuntu 20.04 contains meson 0.53.2, but libsigc++ requires meson >= 0.55.0.
        # Install it with pip3 instead of apt.
        sudo pip3 install "meson>=0.55.0"
        export CXX=g++-9
        meson -Dwarnings=fatal _build
        cd _build
        meson compile
    - name: Test
      run: |
        cd _build
        meson test
    - name: Dist
      run: |
        sudo apt install git --yes
        # dist runs setup again so we need to specify CXX again.
        export CXX=g++-9
        cd _build
        meson dist
